---
title: "multiclass"
author: "Zejia Liu"
date: "2023-04-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)

# Read in the training data
training_data <- read_table("training_data.txt")

# Preprocess data as needed
# Create multi classification variable in both data frames
training_data$classification <- ifelse(training_data$activity == 1, "1",
                                       ifelse(training_data$activity == 2, "2",
                                              ifelse(training_data$activity == 3, "3",
                                                     ifelse(training_data$activity == 4, "4",
                                                            ifelse(training_data$activity == 5, "5",
                                                                   ifelse(training_data$activity == 6, "6",
                                                                          "7"))))))
training_data$multi_classification <- ifelse(training_data$classification == "1", 1,
                                             ifelse(training_data$classification == '2', 2,
                                                    ifelse(training_data$classification == '3', 3,
                                                           ifelse(training_data$classification == '4', 4,
                                                                  ifelse(training_data$classification == '5', 5,
                                                                         ifelse(training_data$classification == '6', 6,
                                                                                7))))))
training_data <- subset(training_data, select = -c(activity,classification))
Training_set = training_data[1:4500,]
Testing_data = training_data[4501:7767,]

library(MASS)
# Fit the LDA model
lda_model <- lda(multi_classification ~ ., data = Training_set)

# Make predictions on the test data
test_pred <- predict(lda_model, Testing_data)
lda_class <- test_pred$class
lda_class
# View the predicted class probabilities
#test_pred$posterior

# Read in testing data
test_data <- read_table("test_data.txt")
test_fit <- predict(lda_model, newdata = test_data, type = "response")
test_data$lda_test_class <- test_fit$class
test_data$lda_test_class

# Convert to data frame
test_data_df <- as.data.frame(test_data$lda_test_class)

# Write to file
write_delim(test_data_df, file = "multiclass.txt", delim = "\t", col_names = FALSE)

```

```{r}
# Calculate accuracy
true_labels <- Testing_data$multi_classification
predicted_labels <- lda_class
conf_mat <- table(true_labels, predicted_labels)
accuracy <- sum(diag(conf_mat))/sum(conf_mat)
print(paste("Accuracy:", round(accuracy, 4)))

```

